package entornoGrafico;


import DAO.ContactoDAO;
import entidad.Contacto;
import static entornoGrafico.Agenda2.cv;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;


public class ContactoEG extends javax.swing.JFrame {
    static ContactoDAO bbddContactos = new ContactoDAO();
    static ArrayList<Contacto> listaContactos = new ArrayList<Contacto>();
    static SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    static int pos=0;
    static int fin=0;
    
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactoEG().setVisible(true);
            }
        });
    }
    
    public ContactoEG(){
        initComponents();
           
        listaContactos=bbddContactos.seleccionar();
        mostrarContacto();
    }
    
    public void mostrarContacto(){
        listaContactos=bbddContactos.seleccionar();
        Contacto cont=listaContactos.get(pos);
        fin=listaContactos.size()-1;
              
        jTextField1.setText(Integer.toString(cont.getId()));
        jTextField2.setText(cont.getNombre());
        jTextField3.setText(cont.getApellido1());
        jTextField4.setText(cont.getApellido2());
        jTextField5.setText(cont.getTelefono());
        jTextField6.setText(df.format(cont.getFechaNac()));
        jTextField7.setText(cont.getCiudad());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Ciudad");

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido1");

        jLabel5.setText("Apellido2");

        jLabel6.setText("Telefono");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setText("jTextField5");

        jTextField6.setText("jTextField6");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jButton1.setText(">>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("<");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText(">");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setText("Actualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Nuevo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Borrar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Contacto por ciudades");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel8.setText("Fecha Nac");

        jTextField7.setText("jTextField7");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(27, 27, 27)
                                .addComponent(jButton5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton5)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //BOTON QUE NOS SITUA EN EL EXTREMO DERECHO
        pos=fin;
        mostrarContacto();        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //BOTON QUE NOS SITUA EN EL EXTREMO IZQUIERDO
        pos=0;
        mostrarContacto();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //BOTON QUE RETROCEDE UNA POSICION
        pos--;
        if(pos>=0){
           mostrarContacto();
        }
        else{
            JOptionPane.showMessageDialog(null, "PRINCIPIO. No hay mas contactos");
            pos=0;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //BOTON QUE AVANZA UNA POSICION
        pos++;         
        if(pos<=fin){
           mostrarContacto();
        }
        else{
            JOptionPane.showMessageDialog(null, "FIN. No hay mas contactos");
            pos=fin;
        } 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //BOTON QUE ACTUALIZA
        int idAnt=listaContactos.get(pos).getId();
        Contacto contNuevo=lecturaDatos();
        if(contNuevo!=null){
            bbddContactos.actualizar(contNuevo,idAnt);
            JOptionPane.showMessageDialog(null,"Contacto actualizado");
            mostrarContacto();         
        }else{
            JOptionPane.showMessageDialog(null,"El contacto NO se ha actualizado");
        }       
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //BOTON QUE ELIMINA
        int id=listaContactos.get(pos).getId();
        bbddContactos.eliminar(id);
        JOptionPane.showMessageDialog(null,"Contacto eliminado");
        pos--;
        mostrarContacto(); 
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       //BOTON QUE INTRODUCE CONTACTO
        if(jButton6.getText().equals("Nuevo")){
        
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
                     
          jButton6.setText("Añadir");  
        }else{
           Contacto contNuevo=lecturaDatos();
           if(contNuevo!=null){
            bbddContactos.insertar(contNuevo);
            JOptionPane.showMessageDialog(null,"Contacto creado");
            jButton6.setText("Nuevo");  
            mostrarContacto();            
           }else{
            JOptionPane.showMessageDialog(null,"El contacto NO se ha creado");
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //BOTON QUE HACE VISIBLE LA VENTANA DE ContactoCiudad
        cv = new ContactoCiudad();
        cv.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed
      
    public Contacto lecturaDatos(){
        String idStr,nom,ape1,ape2,tel,fechaStr,diaSt,mesSt,anyoSt,ciudad;
        int id;
        int pos1=0,pos2=0;
        Date fechaNac;
        boolean swID=false,swNom=false,swApe1=false,swApe2=false,swTel=false,swFecha=false,swCiudad=false;
        Contacto contNuevo = new Contacto();
                        
        idStr=jTextField1.getText();
        if(idStr.isEmpty()==true){
            JOptionPane.showMessageDialog(null, "ERROR.El campo ID no puede estar vacio");
        }else{
            if(isIntegerPositive(idStr)==false){
             JOptionPane.showMessageDialog(null, "ERROR.Debe introducir un numero positivo en el campo ID");
            }else{
                id=Integer.parseInt(idStr);
                contNuevo.setId(id);
                swID=true;
            }
        }
        nom=jTextField2.getText();
        if(nom.isEmpty()==true){
            JOptionPane.showMessageDialog(null, "ERROR.El campo NOMBRE no puede estar vacio");
        }else{
            contNuevo.setNombre(nom);
            swNom=true;
        }
        ape1=jTextField3.getText();
        if(ape1.isEmpty()==true){
            JOptionPane.showMessageDialog(null, "ERROR.El campo APELLIDO1 no puede estar vacio");
        }else{
            contNuevo.setApellido1(ape1);
            swApe1=true;
        }
        ape2=jTextField4.getText();
        if(ape2.isEmpty()==true){
            JOptionPane.showMessageDialog(null, "ERROR.El campo APELLIDO1 no puede estar vacio");
        }else{
            contNuevo.setApellido2(ape2);
            swApe2=true;
        }
        tel=jTextField5.getText();
        if(tel.isEmpty()==true){
            JOptionPane.showMessageDialog(null, "ERROR.El campo TELEFONO no puede estar vacio");
        }
        else{
            if(isIntegerPositive(tel)==false || tel.length()!=9){
                JOptionPane.showMessageDialog(null, "ERROR.El TELEFONO ha de ser un NUMERO de 9 DIGITOS");
            }else{
                contNuevo.setTelefono(tel);
                swTel=true;
            }
        }
        fechaStr=jTextField6.getText();
        if(fechaStr.isEmpty()==true){
            JOptionPane.showMessageDialog(null, "ERROR.El campo FECHA NACIMIENTO no puede estar vacio");
        }else{
            pos1=fechaStr.indexOf("/");
            pos2=fechaStr.indexOf("/",pos1+1);
            if(pos1==0 || pos2==0){
                JOptionPane.showMessageDialog(null, "ERROR DE FORMATO. Debe ser DD/MM/AAAA");
            }else{
                diaSt=fechaStr.substring(0,pos1);
                mesSt=fechaStr.substring(pos1+1,pos2);
                anyoSt=fechaStr.substring(pos2+1);
                fechaNac=fechaValidada(diaSt,mesSt,anyoSt);
                if(fechaNac!=null){
                    contNuevo.setFechaNac(fechaNac);
                    swFecha=true;
                }
            }
        }
        ciudad=jTextField7.getText();
        if(ciudad.isEmpty()==true){
            JOptionPane.showMessageDialog(null, "ERROR.El campo CIUDAD no puede estar vacio");
        }else{
            contNuevo.setCiudad(ciudad);
            swCiudad=true;
        }
        if(swID==true&& swNom==true&& swApe1==true&& swApe2==true&& swTel==true&& swFecha==true&& swCiudad==true){
            return contNuevo;         
        }else{
            return null;
        }
        
    }
    
    public Date fechaValidada(String diaS,String mesS,String añoS){
            Date fecha = new Date();
            int dia=0,mes=0,año=0,añoActual;
            boolean isDia=false,isMes=false,isAño=false;

            SimpleDateFormat df = new SimpleDateFormat("yyyy");
            añoActual=Integer.parseInt(df.format(fecha));
           
            if(isIntegerPositive(diaS)==true){
                dia=Integer.parseInt(diaS); 
                if(dia>0 && dia<32){
                  isDia=true;
                }
           }
            if(isIntegerPositive(mesS)==true && isDia==true){
                mes=Integer.parseInt(mesS);
                if(mes>0 && mes<13){
                    isMes=true;
                    if(mes==2 && dia>29)
                            isMes=false;
                    if((mes==4 || mes==6 || mes==9 || mes==11) && dia>30)
                            isMes=false;

                }
            }

            if(isIntegerPositive(añoS)==true && isDia==true && isMes==true){
                año=Integer.parseInt(añoS);;
                if(año>1900 && año<=añoActual){
                    isAño=true;
                    if(año%4!=0 && mes==2 && dia==29)
                        isAño=false;
                 
                }
            }
          
            
            if(isDia==true && isMes==true && isAño==true){
                GregorianCalendar fechaCal = new GregorianCalendar(año,mes-1,dia);
                fecha=fechaCal.getTime();
                return fecha;
            }else{
                JOptionPane.showMessageDialog(null, "ERROR en la introducción de la fecha");
                return null;
            }
    }
    public boolean isIntegerPositive(String cadena){
        boolean swIntegerPositive=true;
        int i=0;

            while(i<cadena.length() && swIntegerPositive==true){
                if((cadena.charAt(i)<48 || cadena.charAt(i)>57)){
                        swIntegerPositive=false;
                }
                i++;
            }
       
        return swIntegerPositive;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
